apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - image: ghcr.io/yash-negi/vote:c82a8cc5a3652386feb8598d0d527a4f25af1374
        name: vote
        ports:
        - containerPort: 80
          name: vote
